#!/bin/bash
# create a rar file in cbr extension
# cbr <dir>

echo Create a CBR file for $1

if [ $# == 1 ]; then
    rar a -r -m0 -df $1.cbr $1
fi

if [ $# == 2 ]; then
    rar a -r -m0 -df $2.cbr $1
fi

