#!/bin/bash
# restore from a tbz file to docker volume
# two arguments:
#     path to file
#     volume name

if [ $# == 2 ]; then
    echo restore volume backup from $1 to $2

    ABS=`readlink --canonicalize $1`
    DIR=`dirname $ABS`
    FILE=`basename $ABS`

    echo loading from $ABS
    docker run -it --privileged=true \
        -v $2:/volume \
        -v $DIR:/backup alpine \
            sh -c "rm -rf /volume/* /volume/..?* \
                  /volume/.[!.]*; tar -C /volume/ -xvjf /backup/$FILE"
else
    echo 'need parameters: absolute path to file origin and volume name destination'
fi

