#!/bin/bash

# two arguments:
#     volume name
#     path to file
echo making backup of $1 in $2

DIR=`dirname $2`
FILE=`basename $2`

docker run -it --privileged=true \
    -v $1:/volume \
    -v $DIR:/backup alpine \
        tar -cvjpf /backup/$FILE -C /volume ./

