#!/bin/bash

# two arguments:
#     volume name
#     path to file
if [ $# == 2 ]; then
    echo making backup of $1 in $2

    ABS=`readlink --canonicalize $2`
    DIR=`dirname $ABS`
    FILE=`basename $ABS`

    echo saving on $ABS
    docker run -it --privileged=true \
        -v $1:/volume \
        -v $DIR:/backup alpine \
            tar -cvjpf /backup/$FILE -C /volume ./
else
    echo 'need parameters: volume name origin and absolute path to file destination'
fi

