import globals from 'globals';
import stylistic from '@stylistic/eslint-plugin';

export default [{
    files:[
        '*.js'
    ],
    plugins:{
        '@stylistic':stylistic
    },
    languageOptions:{
        globals:{
            ...globals.node,
            ...globals.mocha,
            Atomics:'readonly',
            SharedArrayBuffer:'readonly'
        },
        ecmaVersion:'latest',
        sourceType:'module',
        parserOptions:{
            ecmaFeatures:{
                jsx:true
            }
        }
    },
    rules:{
        // eslint: possible problems
        'array-callback-return':['error'],
        'constructor-super':['error'],
        'for-direction':['error'],
        'getter-return':['error'],
        'no-async-promise-executor':['error'],
        //'no-await-in-loop':['error'],
        'no-class-assign':['error'],
        'no-compare-neg-zero':['error'],
        'no-cond-assign':['error'],
        'no-const-assign':['error'],
        'no-constant-binary-expression':['error'],
        'no-constant-condition':['error'],
        'no-constructor-return':['error'],
        'no-control-regex':['error'],
        'no-debugger':['error'],
        'no-dupe-args':['error'],
        'no-dupe-class-members':['error'],
        'no-dupe-else-if':['error'],
        'no-dupe-keys':['error'],
        'no-duplicate-case':['error'],
        'no-duplicate-imports':['error'],
        'no-empty-character-class':['error'],
        'no-empty-pattern':['error'],
        'no-ex-assign':['error'],
        'no-fallthrough':['error'],
        'no-func-assign':['error'],
        'no-import-assign':['error'],
        'no-inner-declarations':['error'],
        'no-invalid-regexp':['error'],
        'no-irregular-whitespace':['error'],
        'no-loss-of-precision':['error'],
        'no-misleading-character-class':['error'],
        'no-new-native-nonconstructor':['error'],
        'no-obj-calls':['error'],
        'no-promise-executor-return':['error'],
        'no-prototype-builtins':['error'],
        'no-self-assign':['error'],
        'no-self-compare':['error'],
        'no-setter-return':['error'],
        'no-sparse-arrays':['error'],
        'no-template-curly-in-string':['error'],
        'no-this-before-super':['error'],
        'no-unassigned-vars':['error'],
        'no-undef':['error'],
        'no-unexpected-multiline':['error'],
        'no-unmodified-loop-condition':['error'],
        'no-unreachable':['error'],
        'no-unreachable-loop':['error'],
        'no-unsafe-finally':['error'],
        'no-unsafe-negation':['error'],
        'no-unsafe-optional-chaining':['error'],
        'no-unused-private-class-members':['error'],
        'no-unused-vars':['error'],
        'no-use-before-define':['error'],
        'no-useless-assignment':['error'],
        'no-useless-backreference':['error'],
        //'require-atomic-updates':['error'],
        'use-isnan':['error'],
        'valid-typeof':['error'],

        // eslint: suggestions
        'accessor-pairs':['error'],
        'arrow-body-style':['error','always'],
        'block-scoped-var':['error'],
        'camelcase':['error',{
            'properties':'never'
        }],
        //'capitalized-comments':['error'],
        //'class-methods-use-this':['error'],
        //'complexity':['error'],
        'consistent-return':['error'],
        'consistent-this':['error'],
        'curly':['error'],
        'default-case':['error'],
        'default-case-last':['error'],
        'default-param-last':['error'],
        'dot-notation':['error'],
        'eqeqeq':['error'],
        'func-name-matching':['error'],
        'func-names':['error','never'],
        'func-style':['error'],
        'grouped-accessor-pairs':['error'],
        'guard-for-in':['error'],
        'id-denylist':['error'],
        'id-length':['error',{
            'exceptions':['$','i','j','k']
        }],
        'id-match':['error'],
        //'init-declarations':['error'],
        'logical-assignment-operators':['error'],
        'max-classes-per-file':['error'],
        'max-depth':['error',6],
        //'max-lines':['error'],
        //'max-lines-per-function':['error'],
        'max-nested-callbacks':['error'],
        'max-params':['error',5],
        //'max-statements':['error'],
        'new-cap':['error',{
            'properties':false
        }],
        'no-alert':['error'],
        'no-array-constructor':['error'],
        'no-bitwise':['error'],
        'no-caller':['error'],
        'no-case-declarations':['error'],
        //'no-console':['error'],
        'no-continue':['error'],
        'no-delete-var':['error'],
        'no-div-regex':['error'],
        'no-else-return':['error'],
        'no-empty':['error'],
        'no-empty-function':['error'],
        'no-empty-static-block':['error'],
        'no-eq-null':['error'],
        'no-eval':['error'],
        'no-extend-native':['error'],
        'no-extra-bind':['error'],
        'no-extra-boolean-cast':['error'],
        'no-extra-label':['error'],
        'no-global-assign':['error'],
        'no-implicit-coercion':['error'],
        'no-implicit-globals':['error'],
        'no-implied-eval':['error'],
        //'no-inline-comments':['error'],
        'no-invalid-this':['error'],
        'no-iterator':['error'],
        'no-label-var':['error'],
        'no-labels':['error'],
        'no-lone-blocks':['error'],
        'no-lonely-if':['error'],
        'no-loop-func':['error'],
        //'no-magic-numbers':['error'],
        'no-multi-assign':['error'],
        'no-multi-str':['error'],
        'no-negated-condition':['error'],
        'no-nested-ternary':['error'],
        'no-new':['error'],
        'no-new-func':['error'],
        'no-new-wrappers':['error'],
        'no-nonoctal-decimal-escape':['error'],
        'no-object-constructor':['error'],
        'no-octal':['error'],
        'no-octal-escape':['error'],
        //'no-param-reassign':['error'],
        'no-plusplus':['error',{
            'allowForLoopAfterthoughts':true
        }],
        'no-proto':['error'],
        'no-redeclare':['error'],
        'no-regex-spaces':['error'],
        'no-restricted-exports':['error'],
        'no-restricted-globals':['error'],
        'no-restricted-imports':['error'],
        'no-restricted-properties':['error'],
        'no-restricted-syntax':['error'],
        'no-return-assign':['error'],
        'no-script-url':['error'],
        'no-sequences':['error'],
        'no-shadow':['error'],
        'no-shadow-restricted-names':['error'],
        //'no-ternary':['error'],
        'no-throw-literal':['error'],
        'no-undef-init':['error'],
        'no-undefined':['error'],
        'no-underscore-dangle':['error',{
            'allow':[
                '_id',
                '_rev',
                '_dbserver',
                '_repository',
            ]
        }],
        'no-unneeded-ternary':['error'],
        'no-unused-expressions':['error'],
        'no-unused-labels':['error'],
        'no-useless-call':['error'],
        'no-useless-catch':['error'],
        'no-useless-computed-key':['error'],
        'no-useless-concat':['error'],
        'no-useless-constructor':['error'],
        'no-useless-escape':['error'],
        'no-useless-rename':['error'],
        'no-useless-return':['error'],
        'no-var':['error'],
        'no-void':['error'],
        //'no-warning-comments':['error'],
        'no-with':['error'],
        'object-shorthand':['error','never'],
        //'one-var':['error'],
        'operator-assignment':['error'],
        'prefer-arrow-callback':['error'],
        'prefer-const':['error'],
        //'prefer-destructuring':['error'],
        'prefer-exponentiation-operator':['error'],
        //'prefer-named-capture-group':['error'],
        'prefer-numeric-literals':['error'],
        'prefer-object-has-own':['error'],
        'prefer-object-spread':['error'],
        'prefer-promise-reject-errors':['error'],
        //'prefer-regex-literals':['error'],
        'prefer-rest-params':['error'],
        'prefer-spread':['error'],
        //'prefer-template':['error'],
        'preserve-caught-error':['error'],
        'radix':['error'],
        'require-await':['error'],
        'require-unicode-regexp':['error'],
        'require-yield':['error'],
        'sort-imports':['error',{
            'ignoreDeclarationSort':true,
            'allowSeparatedGroups':true
        }],
        //'sort-keys':['error'],
        //'sort-vars':['error'],
        'strict':['error'],
        'symbol-description':['error'],
        'vars-on-top':['error'],
        'yoda':['error'],
        // eslint: layout & formatting
        'unicode-bom':['error'],

        // eslint: deprecated to stylistic
        'array-bracket-newline':['error','consistent'],
        'array-bracket-spacing':['error','never'],
        //'array-element-newline':['error','consistent'],
        'arrow-parens':['error'],
        'arrow-spacing':['error',{
            'before':false,
            'after':false
        }],
        'block-spacing':['error','never'],
        'brace-style':['error','1tbs',{
            'allowSingleLine':false
        }],
        'callback-return':['error'],
        'comma-dangle':['error','never'],
        'comma-spacing':['error',{
            'before':false,
            'after':false
        }],
        'comma-style':['error','last'],
        'computed-property-spacing':['error','never'],
        'dot-location':['error','property'],
        'eol-last':['error','always'],
        'func-call-spacing':['error'],
        'function-call-argument-newline':['error','consistent'],
        'function-paren-newline':['error','consistent'],
        'generator-star-spacing':['error'],
        'global-require':['error'],
        'handle-callback-err':['error'],
        'id-blacklist':['error'],
        'implicit-arrow-linebreak':['error'],
        'indent':['error',4,{
            'SwitchCase':1,
            'VariableDeclarator':1,
            'MemberExpression':0,
            'FunctionDeclaration':{
                parameters:'off',
                body:1
            },
            'FunctionExpression':{
                parameters:'off',
                body:1
            }
        }],
        'jsx-quotes':['error'],
        'key-spacing':['error',{
            'afterColon':false
        }],
        'keyword-spacing':['error',{
            'overrides':{
                'if':{
                    'before':false,
                    'after':false
                },
                'else':{
                    'before':false,
                    'after':false
                },
                'for':{
                    'before':false,
                    'after':false
                },
                'await':{
                    'before':false,
                    'after':false
                },
                'while':{
                    'before':false,
                    'after':false
                },
                'switch':{
                    'before':false,
                    'after':false
                },
                'try':{
                    'before':false,
                    'after':false
                },
                'catch':{
                    'before':false,
                    'after':false
                },
                'finally':{
                    'before':false,
                    'after':false
                }
            }
        }],
        //'line-comment-position':['error'],
        'linebreak-style':['error','unix'],
        'lines-around-comment':['error',{
            'allowBlockStart': true,
            'beforeLineComment':true,
            'allowObjectStart':true,
            'allowArrayStart':true
        }],
        'lines-around-directive':['error'],
        'lines-between-class-members':['error','always',{
            'exceptAfterSingleLine':true
        }],
        'max-len':['error',{
            'code':80
        }],
        'max-statements-per-line':['error',{
            'max':1
        }],
        'multiline-comment-style':['error'],
        'multiline-ternary':['error'],
        'new-parens':['error'],
        'newline-after-var':['error'],
        'newline-before-return':['error'],
        'newline-per-chained-call':['error',{
            'ignoreChainWithDepth':2
        }],
        'no-buffer-constructor':['error'],
        'no-catch-shadow':['error'],
        'no-confusing-arrow':['error'],
        'no-extra-parens':['error','all',{
            'nestedBinaryExpressions':false
        }],
        'no-extra-semi':['error'],
        'no-floating-decimal':['error'],
        'no-mixed-operators':['error',{
            'groups':[['&','|','^','~','<<','>>','>>>'],['&&','||']]
        }],
        'no-mixed-requires':['error'],
        'no-mixed-spaces-and-tabs':['error'],
        'no-multi-spaces':['error',{
            'ignoreEOLComments':true
        }],
        'no-multiple-empty-lines':['error',{
            'max':1,
            'maxBOF':0
        }],
        'no-native-reassign':['error'],
        'no-negated-in-lhs':['error'],
        'no-new-object':['error'],
        'no-new-require':['error'],
        'no-new-symbol':['error'],
        'no-path-concat':['error'],
        //'no-process-env':['error'],
        //'no-process-exit':['error'],
        'no-restricted-modules':['error'],
        'no-spaced-func':['error'],
        'no-sync':['error'],
        'no-tabs':['error'],
        'no-trailing-spaces':['error',{
            'skipBlankLines':false
        }],
        'no-whitespace-before-property':['error'],
        'nonblock-statement-body-position':['error'],
        'object-curly-newline':['error'],
        'object-curly-spacing':['error'],
        'object-property-newline':['error'],
        'one-var-declaration-per-line':['error'],
        'operator-linebreak':['error','after'],
        'padded-blocks':['error','never'],
        'padding-line-between-statements':['error'],
        'quote-props':['error','as-needed'],
        'quotes':['error','single'],
        'rest-spread-spacing':['error'],
        'semi':['error','always'],
        'semi-spacing':['error',{
            'before':false,
            'after':false
        }],
        'semi-style':['error'],
        'space-before-blocks':['error','never'],
        'space-before-function-paren':['error','never'],
        'space-in-parens':['error'],
        //'space-infix-ops':['error'],
        'space-unary-ops':['error'],
        'spaced-comment':['error'],
        'switch-colon-spacing':['error'],
        'template-curly-spacing':['error'],
        'template-tag-spacing':['error'],
        'wrap-iife':['error'],
        'wrap-regex':['error'],
        'yield-star-spacing':['error']
    }
}];

