#!/bin/bash
# retrieve files from a directory that break the 80-line standard
# max80 <dirfile>

if [ $# -lt 1 ]
then
    echo 'Insufficient parameters'
    exit 1
fi

find $1 -type f -iname '*.*' -exec awk 'length > 80 { print FILENAME ": " $0}' {} +

