#!/bin/bash
# transform m4a to mp3 files in a directory
# cd <dirfile>; tomp3

for file in ./*.m4a
do
    name="${file%.*}"
    echo $file" -> "$name".mp3"

    ffmpeg -v 5 -y -i "$file" -acodec libmp3lame -ac 2 -ab 192k "$name.mp3"
done

