#!/usr/bin/env node

if(!process.argv[2]&&!process.argv[3]){
    console.log('Need one parameter, url from tmo');
    process.exit(1);
}

const fs=require('fs')
  , request=require('sync-request')
  , regex=/https?\:\/\/www.tumangaonline.com\/lector\/.*\/(.*)\/(.*)\/(.*)/
  , params=regex.exec(process.argv[2])
  , api_url='https://www.tumangaonline.com/api/v1/imagenes?'
        +'idManga='+params[1]
        +'&idScanlation='+params[3]
        +'&numeroCapitulo='+params[2]

console.log('Reading from',api_url);
var response=request('GET',api_url,{
        headers:{
            'user-agent':'Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0'
          , 'x-requested-with':'XMLHtttpRequest'
          , 'referer':process.argv[2]
          , 'accept':'application/json, text/plain, */*'
          , 'accept-language':'es-419,es;q=0.9'
          , 'cache-mode':'no-cache'
        }
    })
  , api=JSON.parse(response.getBody())
  , images=JSON.parse(api.imagenes)
  , url_image='https://img1.tumangaonline.com/subidas/'
        +params[1]+'/'+params[2]+'/'+params[3]+'/'

fs.mkdirSync(process.argv[3]);

images.forEach((i,j)=>{
    console.log('=>',url_image+i);
    var stream=request('GET',url_image+i,{
            headers:{
                'user-agent':'Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0'
              , 'referer':process.argv[2]
            }
        })

    fs.writeFileSync(process.argv[3]+'/'+
        j.toString().padStart(2,'0')+'.jpg',stream.getBody());
});

