#!/usr/bin/env node

if(!process.argv[2]){
    console.log('Need one parameter, url from tmo');
    process.exit(1);
}

const cheerio=require('cheerio')
  , fs=require('fs')
  , request=require('sync-request')
  , uniq=require('underscore').uniq
  , regex=/https?\:\/\/tumangaonline.me\/viewer\/(.*)\/paginated\/?(.*)/
  , params=regex.exec(process.argv[2])
  , headers={
        headers:{
            'user-agent':'Mozilla/5.0 (X11; Linux i686; rv:10.0) '
                +'Gecko/20100101 Firefox/10.0'
          , 'referer':process.argv[2]
          , 'accept':'application/json, text/plain, *-/*'
          , 'accept-language':'es-419,es;q=0.9'
          , 'cache-mode':'no-cache'
        }
    }

console.log('Reading paginated from: ',process.argv[2]);
var response=request('GET',process.argv[2],headers)
  , text=response.getBody().toString()
  , $=cheerio.load(text)
  , pages=[]

$('select#viewer-pages-select>option').each(function(i,item){
    pages.push(item.attribs.value);
});

pages=uniq(pages);

var url_image='https://tumangaonline.me/viewer/'+params[1]+'/paginated/'
  , dir=''

if(process.argv[3]){
    if(!fs.existsSync(process.argv[3])){
        fs.mkdirSync(process.argv[3]);
    }

    dir=process.argv[3]+'/';
}

pages.forEach((i,j)=>{
    console.log('=>',url_image+i);
    let response1=request('GET',url_image+i,headers)
      , text1=response1.getBody().toString()
      , $1=cheerio.load(text1)
      , src=$1('img.viewer-image')[0].attribs.src

    console.log('=>',src);
    let stream=request('GET',src,{
            headers:{
                'accept':'text/html,application/xhtml+xml,application/xml'
                    +';q=0.9,image/webp,image/apng,*/*;q=0.8'
              , 'accept-encoding':'gzip, deflate, br'
              , 'accept-language':'es-419,es;q=0.9'
              , 'cache-control':'no-cache'
              , 'pragma':'no-cache'
              , 'referer':process.argv[2]
              , 'upgrade-insecure-requests':'1'
              , 'user-agent':'Mozilla/5.0 (X11; Linux i686; rv:10.0) '
                    +'Gecko/20100101 Firefox/10.0'
            }
        })

    fs.writeFileSync(dir+j.toString().padStart(2,'0')+'.jpg',stream.getBody());
    console.log();
});

